### ISSUE TITLE
UI: Nephio branding support

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/one-summit-22-workshop#14]

**Comment by ChristopherFry** [comment]
Branding is now supported in the Config as Data UI. This has been completed with https://github.com/GoogleContainerTools/kpt-backstage-plugins/pull/206 where the UI can be themed via configuration.

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/4991787/201956750-53745adc-d2fd-46a3-879b-9524e425ba04.png">

Config as Data UI App Configuration for Nephio Branding:
```
    backend:
      # Content Security Policy
      csp:
        # Allows images to be pulled from GitHub and Nepio
        img-src: ["'self'", 'data:', 'https://raw.githubusercontent.com', 'https://nephio.org']

  configAsData:
      # Nephio branding customizations
      branding:
        title: Nephio
        header:
          logoUrl: https://raw.githubusercontent.com/nephio-project/one-summit-22-workshop/main/images/nephio_logo_colorwhite_horizontal.svg
          backgroundImageUrl: https://nephio.org/wp-content/uploads/sites/6/2022/04/Hero-1.png
```
